version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/sott0n/go-scheme
    steps:
      - checkout
      - run: go test -v ./scheme